### ISSUE TITLE
Infinite redirect of authentication after page left stale for ~10 minutes or more

### ISSUE THREAD

**Issue by wakurth** [AzureAD/azure-activedirectory-library-for-js#202]
When a user logs into to a web app using adal.js to secure the site, leaves the page stale for ~10 minutes or more, and then interacts with the app in any way (e.g. navigates to a new view or clicks a button that makes a web request), the page enters an infinite loop of authentication. We are using Chrome and IE 11.

*infinite loop:
web app redirect to auzre ad --> azure ad redirect back to web app with token .... repeat

No errors are logged to the console. Often, I have to task-manager-kill the browser to make it stop.

We are using the standard angular.js router.

authConfig:

```javascript
    .constant('authConfig', {
		tenant: '[tenantname]',
		clientId: '[clientId]',
		extraQueryParameter : 'domain_hint=our-domain',
		endpoints: {
		'http://api': '[clientId]'
		}
    })
```

module.config

```javascript

(function() {
  'use strict';

  angular
    .module('myapp')
    .config(config);

  /** @ngInject */
  function config($logProvider,  $httpProvider, adalAuthenticationServiceProvider, authConfig) {
    // Enable log
    $logProvider.debugEnabled(true);

    // Setup adal auth configuration
    adalAuthenticationServiceProvider.init(authConfig, $httpProvider);
  }

})();

```

route.config

```javascript

(function() {
  'use strict';

  angular
    .module('myapp')
    .config(routeConfig);

  function routeConfig($routeProvider) {
    $routeProvider
      .when('/', {
        templateUrl: 'app/main/main.html',
        controller: 'MainController',
        controllerAs: 'vm',
        requireADLogin: true
      })
      .otherwise({
        redirectTo: '/'
      });
  }

})();

```

**Comment by weijjia** [comment]
Can you capture the logs?

**Comment by tushargupta51** [comment]
@wakurth can you try getting logs for this. You can setup logging at verbose level using this in app.js:

**Comment by gabbsmo** [comment]
I have this issue as well. I've pasted my verbose log here: https://gist.github.com/gabbsmo/3055b1ce94684cd66d04fdc56d65d0c5

**Comment by gabbsmo** [comment]
I have also found that the adalIdTokenFrame is created recursively. In my markup I have a infinite nested list i iframes. I'm using 1.0.9 in google chrome. I had this issue in 1.0.8 as well.

**Comment by gabbsmo** [comment]
Here is how I reproduce it:

```
var o = {"adal.access.token.key1ab96cc8-b0b9-43c9-b35a-8fc858a2d516":"","adal.error":"login_required","adal.error.description":"AADSTS50058: User account identifier is not provided.\r\nTrace ID: 19bc6e1c-e71b-49ba-bdfd-0f7bfc538b79\r\nCorrelation ID: 20d78465-a3aa-4f59-b365-78c7d1615121\r\nTimestamp: 2016-04-20 05:29:09Z","adal.expiration.key1ab96cc8-b0b9-43c9-b35a-8fc858a2d516":"0","adal.idtoken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik1uQ19WWmNBVGZNNXBPWWlKSE1iYTlnb0VLWSIsImtpZCI6Ik1uQ19WWmNBVGZNNXBPWWlKSE1iYTlnb0VLWSJ9.eyJhdWQiOiIxYWI5NmNjOC1iMGI5LTQzYzktYjM1YS04ZmM4NThhMmQ1MTYiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC82N2E5NjAxYS1iY2FlLTRiNWQtYmM5NS1kNWViMDFmOTEyNzQvIiwiaWF0IjoxNDYxMDQ0OTgxLCJuYmYiOjE0NjEwNDQ5ODEsImV4cCI6MTQ2MTA0ODg4MSwiYW1yIjpbInB3ZCJdLCJmYW1pbHlfbmFtZSI6IlNtb2xqw6FyIiwiZ2l2ZW5fbmFtZSI6IkdhYnJpZWwiLCJpcGFkZHIiOiI5NS4xOTIuMTQyLjg2IiwibmFtZSI6IkdhYnJpZWwgU21vbGrDoXIiLCJub25jZSI6Ijc2YzdhYWVlLTJhMzktNGQ4NS1hYTA4LWQzMTNkNGY2YzBiOCIsIm9pZCI6IjY4ZmM0NTA2LTk1MDctNDM5Ni1iMTZmLTk4OWQ0MzFkYWE4NSIsInJvbGVzIjpbIlVzZXIiXSwic3ViIjoiU1Y5eWV6YVkwSVp4QWI0WUNwaURVVkJGY21zMjJzemVUOWtRVURtMXliZyIsInRpZCI6IjY3YTk2MDFhLWJjYWUtNGI1ZC1iYzk1LWQ1ZWIwMWY5MTI3NCIsInVuaXF1ZV9uYW1lIjoiZ3Ntb2xAd2F5cy5zZSIsInVwbiI6ImdzbW9sQHdheXMuc2UiLCJ2ZXIiOiIxLjAifQ.LHkZK4of2xMOaOVS_coZKnBUEce_z7tJlm937RjnrGGsI2tZuCsWtcdtT7yhr5RPGubWl8Mb_dKDhc0qw_gAVThBU9ToCLRyFI67grjHO4n4cxbR6D65d03TdgiDwNKz3r89lIir2EEliw_lqdi-vUY4JuG2mO79s0wvFVVIJdhyMBA4J9_nUDXSZ9tI59LgepGKLyZnlEPu0rs-Jl7PPMjSkOXimUf60oIWDOnphO47mLEp9cW1UtC5fqOQenkKxc2EY72_3InjTAkcP5FaP045ZnFCNe6yCano4g3J7GbpZvb8sRgI-IZnpdoT2fuk1LK2iWgrCqcs4jURv44xuw","adal.login.error":"","adal.login.request":"","adal.nonce.idtoken":"5739bf7f-e603-42f6-83cf-1b9686b63eb0","adal.session.state":"44213ce8-16fc-41e6-bb22-e9156baad776","adal.start.page":"/","adal.state.login":"298a3c58-53a3-49fc-9be4-9e38466da38b","adal.token.keys":"1ab96cc8-b0b9-43c9-b35a-8fc858a2d516|"}

localStorage.clear();
Object.keys(o).forEach(function (key) { localStorage.setItem(key, o[key]); });
```

**Comment by sandor11** [comment]
I am also seeing a recursive creation of `adalIdTokenFrame` for `RENEW_TOKEN` requests. I am able to see where `_oauthData.isAuthenticated = true;` is being called, however, a new instance of the application has been raised after assigning `$window.location`, the SPA simply loads with its first page being the `redirectUrl`.

This means every time the iframe loads the new window, directly after the `_adal.callback` you are in a scenario where `_adal._renewActive = false` and `_oauthData.isAuthenticated = true;` and because you have an entirely new instance of the `adalAuthenticationService` so you head straight into another `_adal.acquireToken` call creating new iframes every time, because the new document within the current iframe does not hold the reference to the previous one. This issue will be present in SPA's due to their nature and I have been able to utilize the `angular-ui-router` to cause a state change rather than a location change enabling the termination of the requests. I can provide any other info if you like, otherwise, I will hope to see this fixed soon.

**Comment by tushargupta51** [comment]
@wakurth @gabbsmo can you try 1.0.10? It should fix the infinite redirect. You might need to add `anonymousEndpoints = []` to your init config.

**Comment by polita** [comment]
Please add a comment if you can still repro this in 1.0.10 and we'll look again.

**Comment by siva524** [comment]
I am still getting this issue after keeping Annonymous endpoints to empty array.

**Comment by P4trik** [comment]
It‘s really urgent and I cannot understand how this bug in such a important library is treated by Microsoft...

**Comment by jmprieur** [comment]
@P4trik : did you read the wiki page : https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/FAQs ?

**Comment by rohitnarula7176** [comment]
@P4trik Can you provide a code repro for this along with the fiddler trace. This issue is logged 2 years back and we have not been able to reproduce it at our end.
