### ISSUE TITLE
login_hint and domain_hint parameters need to be removed from the tokens renewal methods

### ISSUE THREAD

**Issue by ischrei** [AzureAD/azure-activedirectory-library-for-js#293]
Hi,

Following internal incident we had, we found that the usage of the login_hint and domain_hint in the iFrame calls is faulty and should be removed (sometimes the user may login with a certain email address that will map to the wrong tenant in AAD. This leads to "_AADSTS50058: User account identifier is not provided_." error returned from AAD in the iFrame.)

Those hints parameters can improve user experience if they are used for the login call to AAD.
As the framework don't know the user's domain before logging it in, ADAL JS documentation (and code sample) can suggest the developers to use those login parameters.

Thanks,
Ido.

**Comment by tushargupta51** [comment]
@ischrei I am closing this issue as we have fixed the case where we were sending email as hint parameters. I know we have open discussions going on internally for a longer term fix but I would prefer to close this specific issue you ran into.

**Comment by RobinHerbots** [comment]
@tushargupta51 , 

Just informational, ...
I'm using  adal.js 1.0.15.  When specifying  a domainhint in the extraqueryparameters I still have the above issue.

```
       extraQueryParameter: `scope=openid,profile,email&domain_hint=${configJs.Authentication.AzureAd.domain}`
```
