### ISSUE TITLE
Endless redirect on access_denied error AADSTS50105

### ISSUE THREAD

**Issue by wvanderdeijl** [AzureAD/azure-activedirectory-library-for-js#463]
Use case: we have a SPA AngularJS application and a user logs on using azure AD that is not granted access to our application. The user is redirected back to our application with `Error :access_denied; Error description:AADSTS50105: The signed in user is not assigned to a role for the application`. However, the `requireADLogin: true` on our default angular route kicks in and the user is immediately redirected back to login.microsoftonline.com. Since the user has a valid session there he is immediately redirect back to our application with the same `access_denied` error and the redirect loops start over again.

The initial login is triggered by `requireADLogin: true` on the route:
```
    $routeProvider
        .when('/foo/:foonr?', {
            template: '......',
            controller: ParamsController,
            controllerAs: '$ctrl',
            requireADLogin: true
        })
        .otherwise('/foo');
```

ADAL setup:
```
    const adalConfig = {
        clientId: '......',
        tenant: '......',
        redirectUri: `${window.location.origin}/adal.html`,
        extraQueryParameter: 'domain_hint=example.com'
    };
    adal.init(adalConfig, $httpProvider);
```

So, we redirect back to a special `adal.html` that does not have the (protected) routes setup to prevent nested iframes as described in the FAQ: https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/FAQs

I've enabled logging for the adal library both in our normal index.html and in the special adal.html and here's what happens during the "infinite" loop. Log lines prefixed with `main` come from the index.html and lines prefixed with `adal` come from the adal.html
```
main Thu, 22 Dec 2016 09:21:53 GMT:1.0.12-INFO: Start login at:https://localhost/
main Thu, 22 Dec 2016 09:21:53 GMT:1.0.12-VERBOSE: Expected state: 2dff1eae-7a9b-44fe-8fa3-d34c535efe22 startPage:https://localhost/
main Thu, 22 Dec 2016 09:21:53 GMT:1.0.12-INFO: Navigate url:https://login.microsoftonline.com/mn.onmicrosoft.com/oauth2/authorize?respo…d=fe33ab7d-517d-40b1-8b1f-637fcb10546a&x-client-SKU=Js&x-client-Ver=1.0.12
main Thu, 22 Dec 2016 09:21:53 GMT:1.0.12-INFO: Navigate to:https://login.microsoftonline.com/mn.onmicrosoft.com/oauth2/authorize?respo…ient-SKU=Js&x-client-Ver=1.0.12&nonce=6f5bf7c4-5e47-414d-9180-906ddbe7ce3b
<<< this is where user logs in and gets redirected back to adal.html >>>
adal Thu, 22 Dec 2016 09:21:54 GMT:1.0.12-VERBOSE: Location change event from https://localhost/adal.html#/error=access_denied&error_description=AADSTS50…Timestamp:+2016-12-22+09:21:55Z&state=2dff1eae-7a9b-44fe-8fa3-d34c535efe22 to https://localhost/adal.html#/error=access_denied&error_description=AADSTS50…Timestamp:+2016-12-22+09:21:55Z&state=2dff1eae-7a9b-44fe-8fa3-d34c535efe22
adal Thu, 22 Dec 2016 09:21:54 GMT:1.0.12-VERBOSE: Processing the hash: #/error=access_denied&error_description=AADSTS50105:+The+signed+in+user+is+not+assigned+to+a+role+for+the+application+'43e5cf1c-25a8-4600-ae2e-14c201159de3'.%0D%0ATrace+ID:+686ca884-d707-4427-82b9-87b299c78d63%0D%0ACorrelation+ID:+fe33ab7d-517d-40b1-8b1f-637fcb10546a%0D%0ATimestamp:+2016-12-22+09:21:55Z&state=2dff1eae-7a9b-44fe-8fa3-d34c535efe22
adal Thu, 22 Dec 2016 09:21:54 GMT:1.0.12-VERBOSE: State: 2dff1eae-7a9b-44fe-8fa3-d34c535efe22
adal Thu, 22 Dec 2016 09:21:54 GMT:1.0.12-INFO: State status:true; Request type:LOGIN
adal Thu, 22 Dec 2016 09:21:54 GMT:1.0.12-INFO: Error :access_denied; Error description:AADSTS50105: The signed in user is not assigned to a role for the application '43e5cf1c-25a8-4600-ae2e-14c201159de3'.
Trace ID: 686ca884-d707-4427-82b9-87b299c78d63
Correlation ID: fe33ab7d-517d-40b1-8b1f-637fcb10546a
Timestamp: 2016-12-22 09:21:55Z
adal Thu, 22 Dec 2016 09:21:54 GMT:1.0.12-VERBOSE: Redirecting to start page: https://localhost/
<<< adal.html initiates redirect to normal homepage at index.html >>>
main Thu, 22 Dec 2016 09:21:56 GMT:1.0.12-VERBOSE: Location change event from https://localhost/ to https://localhost/
main Thu, 22 Dec 2016 09:21:56 GMT:1.0.12-VERBOSE: Location change event from https://localhost/ to https://localhost/foo
main Thu, 22 Dec 2016 09:21:56 GMT:1.0.12-INFO: Route change event for:/foo
main Thu, 22 Dec 2016 09:21:56 GMT:1.0.12-INFO: Login event for:/foo
main Thu, 22 Dec 2016 09:21:57 GMT:1.0.12-INFO: Start login at:https://localhost/
<<< this is the next login redirect which immediate redirects back to adal.html and the loop continues >>>
```

Any idea how to stop this endless loop and simply redirect the user to some failedLogin page where we can show the error?

**Comment by tushargupta51** [comment]
@wvanderdeijl You can listen to adal:loginFailure event and redirect the user to "failedLogin" page.

**Comment by wvanderdeijl** [comment]
Any idea on which scope to setup this listener? I've tried all options I can think of and the listeners never seem to fire. All examples I could find seem to suggest to setup the listener on the scope/controller that triggers the login flow. In my case there isn't any such component as the user doesn't trigger the login flow from a component but we use protected routes

**Comment by rohitnarula7176** [comment]
@wvanderdeijl Can you please share the versions of angular and angular routing you are using. Also if you can share a sample app that reproduces the issue, that would be great. Looking at the route provider, I see that the route with the ParamsController triggers the login flow.  Can you try attaching the listener on that controller?

**Comment by wvanderdeijl** [comment]
I've tried adding the listeners to the controller that is associated with the route but those listeners also don't fire. I've created a sample application with README at https://github.com/wvanderdeijl/adal-hello-world

**Comment by wvanderdeijl** [comment]
Gentle bump

**Comment by wvanderdeijl** [comment]
Is there anything I can do to help the progress of this issue?

**Comment by tushargupta51** [comment]
@wvanderdeijl Sorry for the delay on this. Can you try moving this listener code:

        $scope.$on('adal:loginFailure', (event: any, rejection: any, forResource: any) => {
            debugger;
            console.log('XXXXXXXXXXXXX loginFailure', event, rejection, forResource);
        });

outside of RouteController class in app.ts so that its defined globally in that file or inside .config method of adalAuthenticationServiceProvider, also, please add this listener to rootscope.

We released 1.0.14 yesterday, where we added the functionality to turn off navigating to login start page by default. You might need to set that to false for this to work, property name is navigateToLoginRequestUrl. Please try both with and without setting this property and let us know what you find out.

**Comment by wvanderdeijl** [comment]
Upgrading to 1.0.14 didn't seem to change anything for me. I also tried navigateToLoginRequestUrl=false but that left the user at adal.html on return from Azure AD. We use a different return html than the originating html (index.html) as suggested by the FAQ.

I tried to attach listeners wherever I could, including the $rootScope in both the original index.html and the adal.html AD landing page. The only listeners that fire are the ones on $rootScope in the adal.html. These fire just before ADAL redirects you back to index.html. 

This led to a little trick that seems to work:
```
                $rootScope.$on('adal:loginFailure', (event, rejection, forResource) => {
                    $timeout(() => $window.location.href = '/realerror');
                });
```

This feels like a hack, but it seems to work. It is the $rootScope listener in adal.html that has to use a $timeout to redirect the user after the ADAL redirect. This makes the user navigate to /realerror. Since we use html5 mode this ends up at index.html where we've create a /realerror route that is unprotected by adal.

**Comment by wvanderdeijl** [comment]
Would you be open for a pull request to add a new config option to have a different return URL on authentication failures? This would allow users to return to a non-protected route afterward failures so that non-protected route can be used to show the error.

**Comment by harry671003** [comment]
Facing the same issue. But in angular 2 with ng2-adal. 

When a user does not have any application roles assigned to him, how do we clear the session in the https://login.microsoftonline.com page?

Even though a different user is being selected, the password prompt is not shown, but the page is redirecting to the application page with the same user (the one without application roles assigned).

**Comment by fikkatra** [comment]
Same issue here, running adal-angular 1.0.14. 

I also wonder why Azure AD doesn't handle this for us. Why can't it show an error page to the user, explaining what went wrong? I guess some client applications want to handle this error themselves, but I'm pretty bumped out that I need to provide a screen myself.

**Comment by fikkatra** [comment]
For me, the trick

                $rootScope.$on('adal:loginFailure', (event, rejection, forResource) => {
                    $timeout(() => $window.location.href = '/realerror');
                })

doesn't work. The app is redirected to /realerror, but after that it still redirects to the login page, resulting in an infinite loop. Sometimes it works, sometimes it doesn't, seems like a race condition that even the $timeout can't solve. Especially on IE it always ends up looping.

Is there a way to prevent ADAL from redirecting to the login page upon error, e.g. by calling some code in the adal:loginFailure event handler?

**Comment by fikkatra** [comment]
I can confirm this works in all browsers:

```
$rootScope.$on("adal:loginFailure", () => {
	$state.go("error");
});
```
but only if you set navigateToLoginRequestUrl to false:
```
adalAuthenticationServiceProvider.init(
	{
		...
		navigateToLoginRequestUrl: true
	},
	$httpProvider
);
```
However, we do not want to set this flag to false, as we want to redirect the user to the original page after login (not necessarily the redirectUrl configured in AzureAD).

I think @wvanderdeijl 's suggestion to provide a different redirect url in case of login failure, is a good solution.

**Comment by Jingkun-Hu** [comment]
I encountered same issue, When I used a user to login it is ok, but I try another it showed the error. I use IdentityServer4&app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions{}) to  Office365

**Comment by Jingkun-Hu** [comment]
I got this answer :
This issue has been resolved - it appears that app assignments based on groups only work using top-level groups rather than nested groups. I will mark this issue as resolved.  
From https://social.msdn.microsoft.com/Forums/en-US/483d8cf2-90bd-4bf3-bba8-309dd8769b0b/getting-error-message-the-signed-in-user-user-name-removed-is-not-assigned-to-a-role-for-the?forum=WindowsAzureAD

**Comment by rohitnarula7176** [comment]
fixed

**Comment by fikkatra** [comment]
@rohitnarula7176 What do you mean by 'fixed'? Fixed in the next version?

**Comment by aciccarello** [comment]
This is still an issue when running version 1.0.15. As @fikkatra mentioned, the `$timeout(() => $window.location.href = '/realerror');` does not seem to work well in IE.

I think @Jingkun-Hu fixed his issue by avoiding the error altogether but for valid instances of the error apps should not be thrown into a loop.

**Comment by marcoforce** [comment]
I'm also currently experiencing the error. I'm using 'adal5services' and 'adal-angular5'. I have already requested help via stackoverflow you can check this out 
[](https://stackoverflow.com/questions/50244736/adal5-angular-looping-error-in-the-url-instead-of-showing-a-ui-when-user-is-not)

 I cant apply the solution provided here, since we are using typescript or I don't know how to apply it for me.
