### ISSUE TITLE
Adal Infinite redirection + Edge + Trusted sites

### ISSUE THREAD

**Issue by manishrasrani** [AzureAD/azure-activedirectory-library-for-js#537]
Hi,

**Background:**
I have a single page app (built using Angular) which uses adal and adal-angular to authenticate against Azure Active Directory.
Have been using version 1.0.7 of adal and adal-angular (tried using 1.0.14 as well but still no luck) and ui-router for routing.

**Issue:**
Few of our users are getting continuous authentication loop while trying to access the web application on Edge browser specifically.
Note that it works fine with IE, Chrome and Firefox. Surprisingly it also works fine when Edge is opened in InPrivate window.
This issue is device specific, user specific and only occurs in Edge.

**Workaround:**
When my site is added to the trusted sites (via Control Panel -> Internet Options), the authentication loop issue is resolved and everything works seamlessly.

Any idea why this is happening?
From what I’m assuming as of now is that it’s a cookie issue when adal writes to the auth cookie to the site and Edge can’t seem to read it?

Also any suggestions for a better fix/workaround for this? As I can’t tell all my users to go and add my website to their trusted sites collection.

Code snippet of app.js:

function authenticationInit(adalAuthenticationServiceProvider, $httpProvider, $locationProvider) {
        $locationProvider.html5Mode(false);
        var endpoints = {
            // Map the location of a request to an API to a the identifier of the associated resource
            "EndPointKey": window.config.aadEndPointUrl,
            "EndPointValue": window.config.aadResouceIdUrl
        };

        adalAuthenticationServiceProvider.init(
                  {
                      instance: window.config.AADAuthenticationInstance,
                      tenant: window.config.tenant,
                      clientId: window.config.clientId,
                      extraQueryParameter: 'nux=1',
                      endpoints: endpoints
                  }, $httpProvider);
    }

function registerRoutes($stateProvider) {

        $stateProvider
            .state('home', {
                templateUrl: getViewUrl('widgets'),
                controller: 'WidgetsController',
                controllerAs: 'widget',
                url: '/dashboard'
            })
             .state('terms',
            {
                templateUrl: getViewUrl('terms'),
                controller: 'TermsController',
                controllerAs: 'terms',
                url: '/terms'
            })
}

$rootScope.$on('$locationChangeStart', function (e) {
            if (adalAuthenticationService.userInfo.isAuthenticated == false) {  // Will be executed during first time login and token expiration
                adalAuthenticationService.login();
            }
        });

$rootScope.$on("adal:loginSuccess", function (e) {  // Will be executed after AAD authentication is successful 
        NavigationFactory.navigateTo('home');     
       });

**Comment by manishrasrani** [comment]
Upon further analysis, I figured out that there is an issue with cacheLocation as sessionStorage in Edge browser for certain users.
After setting cacheLocation as localStorage in my adalAuthenticationServiceProvider.init config, the issue was resolved.
I wouldn’t prefer using localStorage for its own disadvantages and security concerns.
As of now I have written conditional code to set cacheLocation as localStorage for only Edge browsers and sessionStorage for others.

Has anyone else faced a similar issue and had a better way to solve it?

**Comment by riteshbhoi** [comment]
I see same issue with edge. But same issue is not reproduced with chrome. Also when i deployed my website on azure and use https url, issue doesn't occur even on edge. Its just when i deploy my website to a local deb box without secured url, i see this issue.

**Comment by manishrasrani** [comment]
@riteshbhoi - Unfortunately for me my website is hosted on azure on a microsoft domain and its configured to use https, but few of my users still get the issue.

**Comment by ukphillips** [comment]
Is this just edge or IE 11 as well?

**Comment by manishrasrani** [comment]
@ukphillips - This issue is only for Edge and it works fine in IE 11, Chrome and Firefox

**Comment by jmprieur** [comment]
@riteshbhoi : would it be only on a specific version of Edge? (Microsoft Edge 40.15063.0.0) ?

**Comment by richarjain** [comment]
I am facing same issue. Adal Infinite redirection in Edge. Can anybody help me out in this

**Comment by komal2302** [comment]
I'm also facing the same issue. Any pointers on how to solve this.

**Comment by topher-slalom** [comment]
@jmprieur , I'm experiencing this only on that version of edge, do you know why this version has this problem?

**Comment by jmprieur** [comment]
@topher-slalom : did you try with the latest version of adal.js ?

**Comment by topher-slalom** [comment]
@jmprieur  1.0.15, and only in an InPrivate window.  Works fine otherwise.

**Comment by rohitnarula7176** [comment]
@topher-slalom if this only happens in Edge private mode, then it is a browser issue. We can't change anything in the library to fix this.

**Comment by topher-slalom** [comment]
@rohitnarula7176 Right, I get that.  Above @jmprieur had asked if someone was seeing this on a specific version of edge, leading me to believe that maybe he was aware of some known Edge issue that I could take a look at.  I wasn't expecting a fix for the library.

**Comment by hkusulja** [comment]
Any progress on resolving this issue?

**Comment by Codefearingguy** [comment]
Stuck with this same issue. Infinite loop of redirects when I try to login using IE 11 & Edge. Works fine in other browsers. Additionally, I have ADFS federation with seamless auth for IE , but the redirects is driving me nuts. Any help is much appreciated.

**Comment by sea1jxr** [comment]
@jmprieur, I am still seeing this in Microsoft Edge 42.17134.1.0

**Comment by jmprieur** [comment]
@navyasric, I let you answer  se1jxr
