### ISSUE TITLE
SharePoint Online after login first load ms graph data not being retrieved

### ISSUE THREAD

**Issue by fbn10040** [AzureAD/azure-activedirectory-library-for-js#660]
In SharePoint Online, after clearing cache and cookies, many web parts makes various calls to the MS Graph API. In order for a call to happen, it needs to go through the ADAL authentication flow. I followed the tutorial from Julie and made modification as to this issue #557. Also I do have the latest 1.0.15.min version running.
In the first load, after page reloads like 2 or 3 times and observing the console log, the data from the API does not render on my page. Instead, looking at the Elements tab (in chrome dev tools), I notice that data was retrieved but inside the iframe with id "adalRenewFramehttps://graph.microsoft.com".
Looking at the console for my custom logs I see that the tokenPromise fails (therefore not rendering the items on my html page). Also, the tokenPromise succeeds for the items in the iframe.
If I reload the page, everything works. After a while though, since token most likely expired, same thing occurs. Any help on this would be appreciate it. Many thanks.
My code [here](https://gist.github.com/fbn10040/d773f594b7b26bf14d75058b215ced19)

Also, not sure if I should place this in a different issue, but the page reloading more than once could cause bad user experience. How can I make this silent?

**Comment by rohitnarula7176** [comment]
@fbn10040 I have fixed your code to ensure that api gets rendered on the first call and not on reloading the page and it is attached below. As far as the number of reloads are concerned, you should see one reload at the time of login where you receive the redirect response on the main page like localhost:3000/#id_token=, second reload when adal removes the token from the url and takes you back to your loginStartPage, and the third reload when you call acquireToken, in which case the page gets loaded inside the hidden iframe. In total you should see 3 reloads and it is by design as Adal relies on the redirect mechanism to receive tokens. To avoid the reloads, you can specify a different redirectUri to receive the token. Please refer to adal's wiki page to see how you can do this.
```
 <script class="pre">
        console.log("app loaded");
        var ADALGraph = {};
        (function() {
            'use strict';
            /* IE fix for window.location.orgin */
            if (!window.location.origin) {
                window.location.origin = window.location.protocol + "//" + window.location.hostname + (window.location.port ? ':' + window.location.port : '');
            }
            /****** CONFIGURATION FILES *******/
            /****** Edit these properties depending on your environment *******/
            var siteCollUrl = window.location.href;

            this.CONSTANTS = {
                TENANT_NAME: 'xxx',
                CLIENT_ID: 'xxx',
                REDIRECT_URL: siteCollUrl
            };
            this.CONFIG = {
                tenant: this.CONSTANTS.TENANT_NAME,
                clientId: this.CONSTANTS.CLIENT_ID,
                redirectUri: this.CONSTANTS.REDIRECT_URL,
                endpoints: {
                    graphUri: 'https://graph.microsoft.com'
                },
                cacheLocation: "localStorage"
            };

            this.authContext = new AuthenticationContext(this.CONFIG);

            this.getAuthToken = function (endpoint) {
                var d = jQuery.Deferred();

                //Read the token from the cache
                var tokenCache = ADALGraph.authContext.getCachedToken(endpoint);
                console.log('ADALGraph->tokenCache for endpoint: ' + endpoint + '\nTokenCache: ' + tokenCache);

                if (tokenCache == undefined) {
                    //If token is undefined, then call AAD to get a new token
                    ADALGraph.authContext.acquireToken(endpoint, function (error, token) {
                        if (error || !token) {
                            d.reject(error);
                        }
                        else {
                            d.resolve(token);
                        }
                    });
                } else {
                    d.resolve(tokenCache);
                }
                //Return a promise for acquiring token
                return d.promise();
            };

            this.getGraphData = function (graphAPI, callback) {
                    console.log('getGraphData:Authenticated:' + graphAPI);
                    //Get the token, either from the cache or from the server
                    var tokenPromise = this.getAuthToken(this.CONFIG.endpoints.graphUri);
                    var self = this;
                    tokenPromise.then(function (token) {
                        //Promise for token resolved
                        if (token != undefined) {
                            console.log('getGraphData:promiseReturned: graphAPI:' + graphAPI +
                                '\n' + 'Token: ' + token);
                            //Valid token, make a REST call to the MSGraphAPI
                            var meUri = self.CONFIG.endpoints.graphUri + graphAPI;
                            $.ajax
                            ({
                                type: "GET",
                                url: meUri,
                                headers: {
                                    //Include the token
                                    "Authorization": "Bearer " + token
                                }
                            }).done(function (response) {
                                console.log('getGraphData:AJAX->done(): graphAPI:' + graphAPI + '\nResponse below:');
                                callback(response);
                                //return response;
                            }).fail(function (response) {
                                console.log('getGraphData:AJAX->fail(): graphAPI:' + graphAPI + '\nResponse below:');
                                callback(response);
                            });
                        } else {
                            console.log('getGraphData:promisePass: graphAPI:' + graphAPI +
                                '\n' + 'Token NOT obtained');
                        }
                    }, function (error) {
                        console.log('getGraphData:tokenPromiseFailed: graphAPI:' + graphAPI + '\nError below:');
                        callback(JSON.stringify(error));
                    });
                }
        }).apply(ADALGraph);

        // This function is used to handle the redirect response in the case of login and acquireToken which happens inside a hidden iframe
        if (ADALGraph.authContext.isCallback(window.location.hash)) { 
            ADALGraph.authContext.handleWindowCallback(window.location.hash);
        }

        // The same page gets loaded in the iframe when you call acquireToken. This check avoids the calling of the api twice.
        if (window.parent === window) { 

            var user = ADALGraph.authContext.getCachedUser();
            if (!user) {
                ADALGraph.authContext.login();
            }
            else {
                ADALGraph.getGraphData('/v1.0/me/', function (data) {
                    console.log(data);
                });
            }
        }

        
        
    </script>
```

**Comment by fbn10040** [comment]
@rohitnarula7176 - Please help. Still having issues with this (haven't reported yet because I got sidetracked into something else at work). Using Chrome Incognito mode I go into my SharePoint Online site and after authenticating, at login.microsoftonline.com, my SharePoint site loads but WITHOUT the MS Graph API data. When I reload the page, data DOES appear and keeps working on other reloads. Only at first it fails. Checking the first load by opening Dev tool and checking the Elements tab (the source), the data does exist inside the iframe tag with id "adalRenewFramehttps://graph.microsoft.com".

[msGraphAdal.js](https://gist.github.com/fbn10040/d773f594b7b26bf14d75058b215ced19)
```
var ADALGraph = {};
(function() {
    'use strict';
    /* IE fix for window.location.orgin */
    if (!window.location.origin) {
        window.location.origin = window.location.protocol + "//" + 
        window.location.hostname + (window.location.port ? ':' + window.location.port: '');
    }
    /****** CONFIGURATION FILES *******/
    /****** Edit these properties depending on your environment *******/

    var CONSTANTS = {
        TENANT_NAME: function() { return mdrcHelper.getADALTenantName() },
        CLIENT_ID: function() { return mdrcHelper.getADALClientId() },
        REDIRECT_URL: function() { return mdrcHelper.getAppRootComponentsSiteUrl() }
    };
    var CONFIG = {
        tenant: CONSTANTS.TENANT_NAME(),
        clientId: CONSTANTS.CLIENT_ID(),
        redirectUri: CONSTANTS.REDIRECT_URL(),
        endpoints: {
            graphUri: 'https://graph.microsoft.com'
        },
        cacheLocation: "localStorage"
    };

    this.authContext =  new AuthenticationContext(CONFIG);

    this.getAuthToken = function(endpoint){
        var d = jQuery.Deferred();
        
        //Read the token from the cache
        var tokenCache = ADALGraph.authContext.getCachedToken(endpoint);
        console.log('ADALGraph->tokenCache for endpoint: ' + endpoint + '\nTokenCache: ' + tokenCache);
   
        if(tokenCache == undefined) {
            //If token is undefined, then call AAD to get a new token
            ADALGraph.authContext.acquireToken(endpoint, function (error, token) {
                if (error || !token) {
                    d.reject(error);
                }
                else {
                    d.resolve(token);
                }
            });
        }else{
            d.resolve(tokenCache);
        }
        //Return a promise for acquiring token
        return d.promise();
    };

    this.getGraphData = function(graphAPI, callback) {
        console.log('getGraphData:Authenticated:' + graphAPI);  
        //Get the token, either from the cache or from the server
        var tokenPromise = ADALGraph.getAuthToken(CONFIG.endpoints.graphUri);
        tokenPromise.then(function(token) {
            //Promise for token resolved
            if(token != undefined) {
                console.log('getGraphData:promiseReturned: graphAPI:' + graphAPI + 
                    '\n' + 'Token: ' + token);

                //Valid token, make a REST call to the MSGraphAPI
                var meUri = CONFIG.endpoints.graphUri + graphAPI;
                $.ajax
                ({
                    type: "GET",
                    url: meUri,
                    headers: {
                        //Include the token
                        "Authorization": "Bearer " + token
                    }
                }).done(function (response) {
                    console.log('getGraphData:AJAX->done(): graphAPI:' + graphAPI + '\nResponse below:');
                    console.log(response);
                    callback(response);
                    //return response;
                }).fail(function (response) {
                    console.log('getGraphData:AJAX->fail(): graphAPI:' + graphAPI + '\nResponse below:');
                    console.log(response);
                });
            } else {
                console.log('getGraphData:promisePass: graphAPI:' + graphAPI + 
                    '\n' + 'Token NOT obtained');
            }
        }, function(error){
            console.log('getGraphData:tokenPromiseFailed: graphAPI:' + graphAPI + '\nError below:');
            console.log(JSON.stringify(error));
            // AADSTS50058: A silent sign-in request was sent but none of the currently signed in user(s) match the requested login hint
            if (error.indexOf('AADSTS50058') !== -1) {
                // log user again
                console.log('msGraphADAL -> getGraphData:tokenPromiseFailed -> login-in');
                ADALGraph.authContext.login();
            }
        });
    };
   
}).apply(ADALGraph); 
```
[insightsMyModifedItemsWp.js](https://gist.github.com/fbn10040/464576d1ee806bcc3a20de716a4927fd) (calls MSGraph to get data 'my' recently modified items )
```
// calls MSGraph to get data 'my' recently modified items
function insightsUsedScript() {
    console.log('InsightsMeItemsUsed->insightsUsedScript()');

    // This function is used to handle the redirect response in the case of login and acquireToken which happens inside a hidden iframe
    if (ADALGraph.authContext.isCallback(window.location.hash)) { 
        ADALGraph.authContext.handleWindowCallback(window.location.hash);
    }

    // The same page gets loaded in the iframe when you call acquireToken. This check avoids the calling of the api twice.
    if (window.parent === window) { 
        var user = ADALGraph.authContext.getCachedUser();
        if (!user) {
            ADALGraph.authContext.login();
        }
        else {
            var apiCall = "/beta/me/insights/used";
            
            ADALGraph.getGraphData( apiCall, function(results) {
                // process results
            });
        }
    }
}
```

**Comment by rohitnarula7176** [comment]
@fbn10040 What is this second file https://gist.github.com/fbn10040/464576d1ee806bcc3a20de716a4927fd and where is it used?

**Comment by rohitnarula7176** [comment]
@fbn10040 I apologize for the misunderstanding. You have attached 2 files. The second file has a function GetMyRecentFilesWebPart() Does the first file call this as well. What am I supposed to run? Last time you just attached a single file so it was not confusing.

**Comment by fbn10040** [comment]
@rohitnarula7176 - Sorry for the misunderstanding. Last time I had one file but no call to that file, however you added a call to ADALGraph at the bottom of your [modified script](https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/660#issuecomment-346219277) as shown below. Going along with your code as seen below, I have separate out those lines and placed them on the "GetMyRecentFilesWebPart.js" script. Think of "GetMyRecentFilesWebPart.js" script as one web part and the "msGraphAdal.js" file as a reference in the master page. There are two other web parts that uses the "msGraphAdal.js" file as well to make call to other MS Graph APIs in a similar way as the "GetMyRecentFileWebPart.js". Please let me know if I should be doing things differently?
...
```
        }).apply(ADALGraph);

        // This function is used to handle the redirect response in the case of login and acquireToken which happens inside a hidden iframe
        if (ADALGraph.authContext.isCallback(window.location.hash)) { 
            ADALGraph.authContext.handleWindowCallback(window.location.hash);
        }

        // The same page gets loaded in the iframe when you call acquireToken. This check avoids the calling of the api twice.
        if (window.parent === window) { 

            var user = ADALGraph.authContext.getCachedUser();
            if (!user) {
                ADALGraph.authContext.login();
            }
            else {
                ADALGraph.getGraphData('/v1.0/me/', function (data) {
                    console.log(data);
                });
            }
        }
    </script>
```
....

**Comment by fbn10040** [comment]
@rohitnarula7176  - any update on this? Kindly appreciate your help on this.

**Comment by rohitnarula7176** [comment]
@fbn10040 I tried to run your code and I was able to get the graph data on the first reload itself. I did not see any issues. If you are still facing issues, lets schedule a skype call.
